# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eli Støa
email: eli.stoa@ntnu.no
description: > # this means to ignore newlines until "baseurl:"
  Eli Støa er professor ved Institutt for Arkitektur og Billedkunst
  ved NTNU. Hun skriver også jevnlig for Adressa, og denne siden
  består av artiklene derfra.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://simenstoa.github.io" # the base hostname & protocol for your site
twitter_username: simenstoa
github_username:  simenstoa

# Build settings
markdown: kramdown
